# Generated by Django 3.2.5 on 2021-08-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('userhandleId', models.CharField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255, unique=True)),
                ('tweeted_by', models.CharField(max_length=255, null=True)),
                ('tweet', models.TextField(max_length=400000, null=True)),
                ('link', models.URLField(max_length=800, null=True)),
                ('tweeted_date_and_time', models.DateTimeField(null=True)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_letter.keyword')),
            ],
        ),
    ]
