# Generated by Django 3.2.5 on 2021-08-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='keyword_id',
            new_name='keyword',
        ),
    ]
